### ISSUE TITLE
Blank popup shown when trying to create new chart in Google Docs

### ISSUE THREAD

**Issue by hosung** [renanlecaro/mermaid-gdocs#44]
I'm having an issue with creating Mermaid diagrams in Google Docs. Here’s the step-by-step to reproduce the problem:

1. Open a new Google Doc ([docs.new](https://docs.new/)).
2. Go to Extensions > New Chart.
3. A blank popup appears instead of the chart creation interface.

It looks like the popup isn’t loading correctly. I’ve tried clearing my browser cache and cookies, and disabling other extensions, but still no luck!

Thanks in advance for your help.

**Comment by DoomedLizard** [comment]
I experienced the same issue editing an existing graph on an existing google doc. My error was caused by the following.

1. I went to a preexisting google doc, which contained a chart I had already programmed. 
2. Extensions>Edit Selected Chart
3. Instead of a manageable popup, the scale of the mermaid chart was stretched across my screen in a long rectangle that exceeded my screen width. I could see a swath of the graph I was supposed to edit, but I couldn't scroll to see my code (or any other vertical strip of the graph). I couldn't see the "x" to close out either, and "esc" didn't work. To get out of the mermaid popup, I had to reload the document
4. I rebooted, re-signed into google docs, and the issue still held. I don't seem to have an update for Chrome available. I selected all with command A, copied, and pasted  (Command+shift+V) into the google document (outside the graph). This showed everything in the graph was still in place. I could see the text from the hidden links (i.e. "Help" and "update" etc.), my program, and the text from all the nodes.
5. I deleted the chart, reloaded, and tried to create a new graph (in the same document) from the program I'd pasted into the doc. 
6. It gave me the same blank popup described above. I wasn't able to simply paste my text in.
7. Now I'm sad.

**Comment by 99092710-MichaelChen** [comment]
I have experienced the same issues as the previous comments.

**Comment by fkchen-kkday** [comment]
I have same experience.
Here's the log in my js console
```
Failed to load resource: the server responded with a status of 404 ()
885357886-warden_bin_i18n_warden__zh_tw.js:226
Error code = 404, Path = /wardeninit, Message = There was an error during the transport or processing of this request., undefined
```

**Comment by renanlecaro** [comment]
Having a look

**Comment by renanlecaro** [comment]
Could NOT reproduce with any of those : 

- Firefox 127.0.2 on Debian 12.5
- Chromium Version 126.0.6478.126 on Debian 12.5
- Google Chrome  127.0.6533.73  (64-bit) on Windows

Each one of them let me create a graph, save it, edit it. 

I'll need more details, ideally please provide : 
- your OS and browser version
- a screen capture of the issue
- does it happen if you switch to a different browser ? 
- does it happen in a private navigation ? 
- does it happen if you disable all plugins ? 
- can you use https://mermaid.live normally ? 

In the meantime, use right click on the graph / alt text  to get the source and edit in in mermaid.live

![image](https://github.com/user-attachments/assets/b6d66939-5929-4036-a309-3e08532b6814)

**Comment by 99092710-MichaelChen** [comment]
I have been testing on my Mac with both Chrome and Safari and both were failed to popup correct screen.
I could use mermaid.live correctly.

**Comment by 99092710-MichaelChen** [comment]
> I have been testing on my Mac with both Chrome and Safari and both were failed to popup correct screen. I could use mermaid.live correctly.

Mine is working now.

**Comment by fkchen-kkday** [comment]
It's working now too.

**Comment by hosung** [comment]
Closing this issue because the creation UI is working properly now. Thank you!

**Comment by renanlecaro** [comment]
I didn't change a thing, really strange.
