### ISSUE TITLE
Script Error: Exception: Invalid image data

### ISSUE THREAD

**Issue by dirtyren** [renanlecaro/mermaid-gdocs#45]
I am getting this error when the sequence diagram is a little bigger, like, the code is 68 lines long. The image will plot all right inside de plugin, but when clicking insert, this error will pop up: Script Error: Exception: Invalid image data,

![image](https://github.com/user-attachments/assets/8f4a2114-413b-485d-9dc2-d81cb4f5a85a)

**Comment by renanlecaro** [comment]
@dirtyren i think this is because at some size, google refuses to embed the image. The solution for now it to break up the graph into smaller ones, or to copy paste from the mermaid.live editor. 

I upscale the image when inserting to get better print resolution, i'll see if i can stop doing that when the graph gets too big, this way i'll hit the limit later. 

I'll also try to put a more helpfull error message

**Comment by renanlecaro** [comment]
I pushed an update, let me know if the issue is still there

**Comment by dirtyren** [comment]
Hey @renanlecaro , the bug is fixed, tks a lot.
